from src.document_generator.base_document_generator import BaseDocumentGenerator
from src.document_generator.new_tins import NewTinsDocumentGenerator
from src.document_generator.old_tins import OldTinsDocumentGenerator
from src.document_generator.snils import SnilsDocumentGenerator
